version: '3'
services:
  node:
    build:
      context: .
      args:
        NODE_TAG: ${NODE_TAG:-12-alpine}
        APP_USER_ID: ${APP_USER_ID:-0}
        APP_GROUP_ID: ${APP_GROUP_ID:-0}
    working_dir: /sail${THEME_DIR:-}
    user: "${APP_USER_ID:-0}:${APP_GROUP_ID:-0}"
