version: '3'
services:
  silverstripe:
    build:
      context: .
      args:
        - SILVERSTRIPE_WEB_TAG=${SILVERSTRIPE_WEB_TAG}
        - COMPOSER_VERSION=${COMPOSER_VERSION}
        - APP_USER_ID=${APP_USER_ID:-0}
        - APP_GROUP_ID=${APP_GROUP_ID:-0}
    working_dir: /var/www/html/
    volumes:
      - ./vhosts:/etc/httpd/vhosts.d
    environment:
       - DOCUMENT_ROOT=${DOCUMENT_ROOT}
       - SS_DATABASE_SERVER=database
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_SSL_PORT:-443}:443
    user: ${APP_USER_ID:-0}:${APP_GROUP_ID:-0}
    networks:
      sail:
        aliases:
          - "${APP_URL:-silverstripe.test}"
